spring:
  application:
    name: kafka-demo-2

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: article-demo-group-2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.sharedmodel"
        spring.json.value.default.type: com.example.sharedmodel.ArticlePublishedEvent

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8081

app:
  kafka:
    topic: article-events-2
    listen-topic: article-events

logging:
  level:
    com.example.kafkademo2: INFO
    org.springframework.security: INFO
